name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt -r requirements-test.txt
          pip install anyio==3.7.1  # Evitar errores con start_blocking_portal

      - name: Ensure data directory and dummy data
        run: |
          mkdir -p data
          if [ ! -f data/data.csv ]; then
            echo "Creating a dummy data.csv for testing..."
            echo "OPERA,TIPOVUELO,MES,delay" > data/data.csv
            echo "Aerolineas Argentinas,N,3,0" >> data/data.csv
          fi

      - name: Start API in background
        run: |
          source .venv/bin/activate
          uvicorn challenge.api:app --host 0.0.0.0 --port 8000 &

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          source .venv/bin/activate
          pytest --cov=challenge tests/
