name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker compose up -d
          sleep 5  # Da tiempo para que la API arranque

      - name: Run API tests
        run: |
          pytest tests/api --disable-warnings  # Solo pruebas de API

      - name: Stop Docker containers
        run: docker compose down
